### ISSUE TITLE
Forms are not trimming inputs - Insert proposals

### ISSUE THREAD

**Issue by ibrahimtaib** [ibrahimtaib/SE2-01#12]
In insert proposal, I feel like the input isn't trimmed, I couldn't make it work with the database.

A few issues to try out (and test):

If all inputs are whitespace, will the form send it to the backend request?
If multiple keywords are empty, e.g:
"                        ,                            ,                            "

What happens? will they all be added? What if there's one empty keyword in the middle of valid keywords? e.g. "Test,                               , test"

I couldn't make it work, but the request is sent to the backend

**Comment by ibrahimtaib** [comment]
![image](https://github.com/ibrahimtaib/SE2-01/assets/118106544/5b0c572e-450d-4219-b8e5-ad06b6bbb85b)

**Comment by frabacc** [comment]
Will be fixed today. Trying to trim the input in the form. I'll search for docs on react-hook and do it
