### ISSUE TITLE
No feedback when request fails - Insert Proposal

### ISSUE THREAD

**Issue by ibrahimtaib** [ibrahimtaib/SE2-01#13]
When trying to test it, I had an error in the backend but no way of knowing If the request failed (as a user), this can be repeated by adding a programme that doesn't exist in the degree database

**Comment by frabacc** [comment]
Fixed and added feedback, I think it's ready to merge

**Comment by frabacc** [comment]
<img width="660" alt="Screenshot 2023-11-13 233058" src="https://github.com/ibrahimtaib/SE2-01/assets/135204409/6c43623e-cc6e-4235-9c42-7359be844dbd">
