### ISSUE TITLE
Programme/cds should be a dropdown menu of degrees

### ISSUE THREAD

**Issue by ibrahimtaib** [ibrahimtaib/SE2-01#14]
Since in the database in insert proposal cds is a foreign key to the degree table, and since the input you're asking for specifically is the COD_DEGREE, to avoid input errors I'd think that it should be a dropdown menu of TITLE_DEGREE, with the value COD_DEGREE. this way it avoids the problems of checking if the value is correct, tell me what you think about it

**Comment by frabacc** [comment]
They should, i'll fix them.

**Comment by frabacc** [comment]
Fixed

**Comment by frabacc** [comment]
Efficienza ca' fariiii
