### ISSUE TITLE
Students don't have to filter for cds, they have to see only their cds proposals

### ISSUE THREAD

**Issue by frabacc** [ibrahimtaib/SE2-01#41]

**Comment by ibrahimtaib** [comment]
I think this ties with the fact that proposal lists should be different for teachers and students.
A teacher should only see its own _active_ proposals. The button for a student should be to apply, and the one for the teacher should be to delete. For now the teachers page is rendered by using MainPage and passing it the same arguments as the student. 

I think one possible solution is to add an action button in the props for FilterProposal, and pass it the proposal attached to it. This way we could pass them a DeleteButton if it's a teacher, or an ApplyButton if it's a student.

The only thing that remains is to be able to select which filters are available and which aren't. This could be done by having a default object with different booleans set to true, and have a prop object that says which filters shouldn't be shown.

For example, in FilterProposal you could have:

`
const allFilters = {cds: true, supervisor: true, date: true } //imagine all other properties
const visibleFilters = {...allFilters, ...props.disabledFilters} 
`
The second line would merge the two objects, and if a property appears twice it would have the value inside disabledFilters.
THis supposes that disabledFilters would be of the form: {cds: false} if we don't want it to appear

**Comment by ibrahimtaib** [comment]
Tell me what you think about it, or if we should just copy the code into another component and change it up (:-1: )

**Comment by manarrre** [comment]
> I think this ties with the fact that proposal lists should be different for teachers and students. A teacher should only see its own _active_ proposals. The button for a student should be to apply, and the one for the teacher should be to delete. For now the teachers page is rendered by using MainPage and passing it the same arguments as the student.
> 
> I think one possible solution is to add an action button in the props for FilterProposal, and pass it down to the ProposalCard. ProposalCard should then insert the Button and pass it the proposal. This way we could pass them a DeleteButton if it's a teacher, or an ApplyButton if it's a student.
> 
> The only thing that remains is to be able to select which filters are available and which aren't. This could be done by having a default object with different booleans set to true, and have a prop object that says which filters shouldn't be shown.
> 
> For example, in FilterProposal you could have:
> 
> `const allFilters = {cds: true, supervisor: true, date: true } //imagine all other properties const visibleFilters = {...allFilters, ...props.disabledFilters} ` The second line would merge the two objects, and if a property appears twice it would have the value inside disabledFilters. THis supposes that disabledFilters would be of the form: {cds: false} if we don't want it to appear


solved

**Comment by RedonKarakaci** [comment]
> _No description provided._

SOLVED!!!!!
